<?php

namespace Drupal\contacts_demo;

use Drupal\Component\Plugin\PluginInspectionInterface;
use Drupal\Core\Plugin\ContainerFactoryPluginInterface;

interface DemoFlavourInterface extends PluginInspectionInterface, ContainerFactoryPluginInterface {

  /**
   * Returns the label for the flavour manifest.
   *
   * @return string
   *   The label for the flavour manifest.
   */
  public function getLabel();

  /**
   * Returns the description for the flavour manifest.
   *
   * @return string
   *   The description for the flavour manifest.
   */
  public function getDescription();

  /**
   * Returns the module name.
   *
   * @return string
   *   The module name where is placed file with data.
   */
  public function getModule();

  /**
   * Returns the files containing entity details.
   *
   * @return array
   *   Array containing the file paths keyed by the entity type contained in the
   *   files.
   */
  public function getFiles();

  /**
   * Returns the number of entities in manifest.
   *
   * @return int
   *   The number of entities in manifest.
   */
  public function count();


  /**
   * Generates content based on manifest.
   */
  public function generate();

  /**
   * Deletes content generated by manifest.
   */
  public function delete();
}
