# @file
# Travis CI integration.

language: php

php:
  - 5.6
  - 7

env:
  global:
    # Ensure composer is able to apply patches.
    - COMPOSER_EXIT_ON_PATCH_FAILURE=1
    # DRUPAL_TI Testing.
    - SIMPLETEST_DB="mysql://root:@127.0.0.1/drupal_travis_db"
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"

  matrix:
    # Latest stable release
    - DRUPAL_CORE="~8.0@stable"
    # Latest dev branch
    - DRUPAL_CORE="~8.0@dev"

    fast_finish: true
    allow_failures:
      - env DRUPAL_CORE="~8.0@dev"

mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8

before_install:
  # Remove xdebug. We aren't generating code coverage, and it slows down Composer.
  - phpenv config-rm xdebug.ini || true
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  # Track our general build directory.
  - export DRUPAL_BUILD_ROOT="$(dirname "$TRAVID_BUILD_DIR")"

install:
  - $TRAVID_BUILD_DIR/travis/install.sh

before_script:
  - $DRUPAL_BUILD_ROOT/vendor/bin/phpcs --config-set installed_paths $DRUPAL_BUILD_ROOT/vendor/drupal/coder/coder_sniffer

script:
  - $DRUPAL_BUILD_ROOT/vendor/bin/phpcs $TRAVID_BUILD_DIR -p --standard=Drupal --colors
  # @todo: Add ESLint
  - php -S localhost:8080 &
  - $DRUPAL_BUILD_ROOT/vendor/bin/phpunit -c $DRUPAL_BUILD_ROOT/web/core/phpunit.xml.dist --group=contacts

notifications:
  email: false
  irc: "chat.freenode.net#freelygive"
