block.settings.custom_text:
  type: block_settings
  label: 'Custom text settings'
  mapping:
    text:
      type: string
      label: 'Custom text'

block.settings.custom_page_title_block:
  type: block_settings
  label: 'Custom page title settings'
  mapping:
    title:
      type: string
      label: 'Page title'
