contacts.contact_tab.*:
  type: config_entity
  label: 'Contact tab config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    path:
      type: string
      label: 'Path'
    weight:
      type: integer
      label: 'Weight'
    relationships:
      type: sequence
      label: 'Relationships'
      sequence:
        type: contacts.relationship.[%name]
        label: 'Relationship'
    block:
      type: contacts.block_plugin.[id]
      label: 'Block'
