contacts.relationship.*:
  type: mapping
  label: 'Relationship'
  mapping:
    id:
      type: string
      label: 'Plugin ID'
    name:
      type: string
      label: 'Context name'
    source:
      type: string
      label: 'Source context'

contacts.block_plugin.*:
  type: block.settings.[id]
  mapping:
    name:
      type: string
      label: 'Name'
    context_mapping:
      type: sequence
      label: 'Context assignments'
      sequence:
        - type: string
    region:
      type: string
      label: 'Region'
    weight:
      type: integer
      label: 'Weight'

block.settings.contacts_entity:*:
  type: block_settings
  mapping:
    mode:
      type: string
      label: 'Mode'
    create:
      type: boolean
      label: 'Create'
    operation:
      type: string
      label: 'Operation'
    view_mode:
      type: string
      label: 'View mode'
    edit_link:
      type: string
      label: 'Edit link'
    edit_id:
      type: string
      label: 'Edit ID'
