# Schema for the configuration files of the crm_tools module.

crm_tools.tools:
  type: config_object
  label: 'CRM Tools settings'
  mapping:
    active_tools:
      type: sequence
      label: 'Active Tools'
      sequence:
        type: boolean
        label: 'Tool'

user.role.*.third_party.crm_tools:
  type: mapping
  label: 'Hat fields'
  mapping:
    crm_tools_is_hat:
      type: boolean
      label: 'Hat'
    crm_tools_color:
      type: text
      label: 'Hat Color'
    crm_tools_icon:
      type: text
      label: 'Hat Icon'
    crm_tools_parent:
      type: string
      label: 'Hat Parent'
